Traceback (most recent call last):
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/samchong/miniforge3/envs/chem502/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Visualise the molecules

mols = [Chem.MolFromSmiles(smiles) for smiles in compounds_smiles.values()]
Draw.MolsToGridImage(mols, molsPerRow=5, legends=compounds_smiles.keys())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 3[0m
[1;32m      1[0m [38;5;66;03m# Visualise the molecules[39;00m
[0;32m----> 3[0m mols [38;5;241m=[39m [[43mChem[49m[38;5;241;43m.[39;49m[43mMolFromSmiles[49m[43m([49m[43msmiles[49m[43m)[49m [38;5;28;01mfor[39;00m smiles [38;5;129;01min[39;00m compounds_smiles[38;5;241m.[39mvalues()]
[1;32m      4[0m Draw[38;5;241m.[39mMolsToGridImage(mols, molsPerRow[38;5;241m=[39m[38;5;241m5[39m, legends[38;5;241m=[39mcompounds_smiles[38;5;241m.[39mkeys())

[0;31mTypeError[0m: No registered converter was able to produce a C++ rvalue of type std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t>> from this Python object of type NoneType

